server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: service-core
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/srb_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456
mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/lggtt/srb/core/mapper/xml/*.xml
#设置日志级别
#logging:
#  level:
#    root: ERROR

